"""Serialize pre-result specifications, never fetch data or simulate returns.

Refuses to overwrite a freeze. Amendments must use a new experiment version.
"""
from pathlib import Path
import json, hashlib, datetime

ROOT = Path(__file__).resolve().parent
shared = {
 'status':'frozen_for_feasibility_only; no return test authorized until data gates pass',
 'capital_usd':2500, 'capital_sensitivity_usd':[1000,5000],
 'development_period':['2016-01-01','2026-09-08'],
 'development_note':'All historical outcomes are exploratory, including newly collected event history. No threshold search.',
 'untouched_validation_period':['2026-10-01','2028-09-29'],
 'validation_policy':'Collect prospectively only after parser and feasibility gates pass before start; otherwise status blocked and freeze a new future window before any outcomes. Do not backfill a missed prospective window. No automatic collection or scheduled task created. Do not inspect interim P&L except risk-stop failure. End-date analysis only; insufficient events is inconclusive.',
 'signal_clock':'America/New_York exchange calendar; documents observed by previous regular-session 16:00. Historical public acceptance plus one complete trading session is the earliest permitted knowledge time; later documented public availability wins. Date-only publication treated as end-of-day plus one session. Unresolved time zone excluded with ledger.',
 'entry_execution':'At 10:00:00 ET on entry session freeze target size and displayed ask limit; decision reaches market at 10:00:05. Fill only at first valid nonlocked SIP ask at/after arrival and within 60 seconds, at/below frozen limit, with displayed ask size >= entire whole-share order. No fill otherwise. One attempt; no chasing or partial-fill assumption. Fill price is eligible ask; separately debit adverse-slippage reserve. No bar-price fill substitution.',
 'exit_execution':'10:00:00 ET on fifth exchange session after entry session, first valid SIP bid after 5-second latency, minus adverse-slippage reserve. Exit is liquidity-taking; if insufficient displayed size use subsequent quote capacity without reusing same displayed inventory; missing depth/quote history is unresolved execution, never a favorable inferred fill. No closing-auction assumptions.',
 'position_sizing':'At decision: floor(min(0.10*marked_equity, settled_cash)/(entry_ask*(1+cost_reserve_rate))). Cash reserve includes both entry and expected exit fees/slippage. Four total positions, one issuer/sponsor, 40% gross cap, no leverage/shorts/fractional shares; no adding. Rank competing events by public knowledge timestamp then CIK then security identifier, not forward returns.',
 'risk_limits':{'drawdown_ceiling':0.25,'new_entry_halt_drawdown':0.20,
   'stop':'Trigger when valid bid <=95% entry fill; model sale at first executable bid after 5 seconds, never at theoretical stop price. Halt/gap can exceed planned 0.5% account loss.',
   'portfolio_halt':'At 20% marked drawdown cancel new entries and liquidate at next feasible bids; absorbing stop for experiment version. Missing held-position quotes/terminal outcomes blocks any pass.',
   'concentration':'One issuer or fund sponsor at a time; report issuer, sponsor, calendar-quarter and asset-type P&L. No manual overrides.'},
 'transaction_costs':{'commission_assumption_usd':0,'base_extra_slippage_bps_per_side':10,
   'stress_extra_slippage_bps_per_side':25,'spread':'Actual observed ask-to-bid crossing charged in addition; never double-count as fee.',
   'fees':'Timestamped applicable regulatory/exchange/broker/action fees separately. Unknown mandatory fees block feasibility. No elective corporate actions.',
   'fixed_cost_sensitivity_usd_per_month':[0,10,25],
   'decision':'Require pass after actual incremental recurring cost; no paid subscription permission inferred.'},
 'latency_stress':'Repeat 60-second arrival and entry delayed by one full session, with same 5-session holding duration; report both without selecting the best. Require positive net event excess in each stress.',
 'cash_and_actions':'Reserve purchase cash immediately. Release sale proceeds on second subsequent exchange business day as a conservative cash-only assumption (not broker entitlement claim). Recognize dividend receivable only on ex-date, release cash only actual payment date. Exact splits/share distributions/delistings, nominal shares and liabilities; unresolved corporate-action accounting blocks pass.',
 'liquidity_filters':'Previous 20 completed sessions median nominal dollar turnover >=$1 million, entry nominal ask >=$5, spread/mid <=0.003, order <=1% lagged median daily dollar turnover. Prior eligible listing history >=20 sessions. Missing delistings/universe records cannot be silently excluded.',
 'benchmarks':['Fully reinvested SPY total return with same period and executable costs',
   '40% SPY/60% zero-interest cash, monthly rebalance, whole shares, same capital/costs',
   'Zero-interest cash and event-specific matched controls; no short portfolio implied'],
 'pass_fail':{
   'data_gate':'At least 90% complete critical fields in preselected document sample; all retained timestamps reconciled, no unresolved critical label; historical universe and quote access demonstrated before any return test. Missing cases retained and selection risk reported.',
   'development_gate':'At least 30 events across >=10 issuer/sponsor clusters; positive net matched excess at base and stress, no concentrated or accounting-driven explanation. Otherwise fail/inconclusive, no retuning.',
   'validation_minimum':'At least 60 completed events across >=15 issuer/sponsor clusters and >=12 distinct entry months; >=24 actually filled portfolio trades per year on average. Otherwise inconclusive or fails opportunity objective, never lower the count after results.',
   'statistical':'Primary metric mean event net total-return excess over predetermined matched controls. Two-candidate family: require one-sided 97.5% lower confidence bound >0 (Bonferroni alpha 0.025 each). 10000 resamples seed 20260909, separately resample issuer/sponsor clusters and contiguous 20-session calendar blocks retaining inactive days and concurrent events; both bounds >0. Repeat 60-session blocks as robustness, also >0. If no defensible matched controls, causal gate fails.',
   'economic':'Validation account CAGR >=5%, greater than 40% SPY/60% cash benchmark, net of actual fixed costs; positive portfolio net at stressed costs; report full SPY comparator without claiming passive outperformance unless actually exceeded.',
   'risk':'Observed marked drawdown <25%, no 20% risk halt; close-only marks insufficient if intraday quote coverage absent.',
   'concentration':'Net P&L excluding top five winning trades remains positive (attribution only); recompute unchanged replay leaving out each issuer/sponsor, require net positive in every run. No issuer/sponsor >25% of gross positive trade P&L. Report all subperiods.',
   'falsification':'Event-specific mechanism controls must pass; positive unadjusted returns alone fail.',
   'execution_gate':'After validation, 60 consecutive live-quote sessions AND >=30 completed local hypothetical trades; extend observations if sparse, no broker orders. >=95% scheduled observation completeness, >=90% predicted fills have supporting post-latency quote capacity; measured 95th percentile adverse slippage <=25 bps/side; actual net expectancy positive including missed fills and all costs. No profitable-stop or implementation automatic approval.'}
}
h1 = {
 'id':'B3-H1-v1','name':'CEF contractual reinvestment route switch',
 'universe':'All US exchange-listed closed-end fund common shares as of event, including later closures/mergers. Must have contemporaneous fund-sponsored plan fixing route at payment-date close and allowing market purchases for at least five subsequent sessions. Exclude plans permitting subsequent issuance switch, ambiguous agent discretion, unproven plan participation and unavailable historical broker eligibility. Current membership is not acceptable.',
 'signal':'Let P be published distribution payment exchange session; if non-session use first following session only when original plan explicitly does so, else exclude. Prior to P+1 10:00, original plan and contemporaneously published P-close NAV/market price plus known commission formula must unambiguously mandate open-market reinvestment. Require documented nonzero plan participation available before entry. Ex-date must precede entry. Distribution and terms known by prior close; otherwise skip this payment event. No minimum discount, yield, momentum or volume signal.',
 'entry_rule':'P+1 exchange session at 10:00 ET, shared execution rules. Route is fixed by contract and data from P, never by later NAV. If inputs unavailable by P+1 09:00 skip rather than move entry.',
 'exit_rule':'Shared fifth-session exit/stop; skip if another previously announced distribution ex-date occurs inside holding interval.',
 'point_in_time_data':['Historical listing/security/sponsor map','Dated original DRIP terms/amendments and agent fee formula','Declared distribution/pay/ex dates and amendments','P-close NAV with actual publication timestamp','P-close market price','Pre-entry evidence of nonzero plan participation','SIP quotes/sizes/conditions/halts','Corporate-action cash/share ledger'],
 'mechanism_falsifiers':'No incremental net effect against issuance-route events and nonpayment placebo windows; inability to establish contractual market demand; apparent effect fully explained by fund NAV/credit/rate exposure. Actual purchases need not be public for prediction, but missing participant evidence fails this stricter version.',
 'controls':'For each treated event use equal-weight all nonmarket-issuance-route funds with same payment session, asset class and leverage flag, listed at event. Need >=3 distinct other sponsors with PIT terms/NAV; otherwise primary event not evaluable, retain in missing-control ledger. Match nearest prior-close NAV discount absolute distance, select three then CIK tie-break. Subtract matched total return with same costs/horizon. Independently compare same-fund window 10 sessions before payment, excluding any other pay/ex event, strictly diagnostic not an optimized entry.',
 'bounded_probe':'Select first three qualifying CEF plan filings in SEC accession order during 2024-01-01..2024-03-31 with text dividend reinvestment and open market (case-insensitive whitespace normalized); inspect at most 30 candidate filings. Require all 3 route rules, historical NAV publication provenance and pre-entry participation evidence. Zero/insufficient eligible examples is data-blocked; do not loosen plan clauses. No prices/returns in probe.'
}
h2 = {
 'id':'B3-M2A-v1','name':'Capped cash-election unwanted-share allocation',
 'universe':'All US-listed REIT/BDC common shares at event with announced elective cash/stock special distribution and binding aggregate cash cap. Include subsequent delistings. Exclude voluntary account participation, rights/tenders, cash-only distributions and unknown historical security identity.',
 'signal':'Original distribution terms plus final public allocation state total requested cash exceeds aggregate cap and cash-electing holders receive stock. Compute unwanted shares=(aggregate requested cash minus actual cash paid to those cash electors)/final allocation share-pricing amount only if each numerator component is explicitly published; shares issued to stock electors are excluded. Require computed value >0; missing cash-election totals means no eligible signal. Final allocation document must be known before scheduled entry under shared clock.',
 'entry_rule':'Third exchange session after publicly scheduled payment date P at 10:00 ET. P is calendar payment date; count strictly later exchange sessions. Do not infer actual broker delivery from P. If final terms unavailable by prior session 16:00, skip; do not shift window or use retrospective credit dates.',
 'exit_rule':'Shared fifth-session exit/stop. Enter ordinary shares only; no election or subscription.',
 'point_in_time_data':['Original distribution/election amendments','Final cash-election demand, cash paid, stock allocation/pricing and public timestamps','Scheduled payment date revision history','Historical REIT/BDC and security listing map','Independent timestamped share delivery evidence for mechanism audit','SIP NBBO sizes/conditions/halts','Nominal stock dividend/split/distribution accounting and delisting outcomes'],
 'mechanism_falsifiers':'No evidence cash electors receive unwanted stock; price effect is split/dilution accounting; all return occurs before delivery; no incremental effect relative to nonbinding cash caps or sector peers; broker delivery dispersed beyond proposed window. Payment+3 is explicitly a testable timing proxy, not a factual credit date.',
 'controls':'Three nearest same-type (REIT vs BDC) issuers by lagged 20-session median dollar turnover, with same broad exposure category from then-public filings; no distribution ex/pay/election in +/-10 sessions; CIK tie-break. Same dates and costs, equal-weight returns. Need PIT exposure category and >=3 controls, otherwise event not evaluable. Separately report all nonbinding capped-cash elections as mechanism negative controls, no outcome-selected subset.',
 'bounded_probe':'First 10 cash/stock election distribution documents by SEC accession from 2023-01-01..2025-12-31 matching cash election AND (proration OR pro rata) AND (REIT OR business development), inspect at most 30 candidate documents and amendments. Include binding/nonbinding/cancelled notices. Require >=9 complete cases including final cash-election demand and pricing, plus dated independent evidence of delivery for at least 3; otherwise data-blocked before price acquisition. Search recall limitations must be audited, not treated as complete universe.'
}
# Clarifications from independent pre-freeze review; no candidate returns viewed.
shared['signal_clock'] = 'America/New_York exchange calendar. Legal/event documents: knowledge time is later of documented public availability and SEC acceptance plus one full exchange session; date-only documents use date-end plus one full session. Required legal documents must be known by prior-session 16:00. Valuation-only P-close NAV/price may arrive through entry-day 09:00 with verified original publication timestamp. This valuation exception never applies to legal/event terms. Unresolved timezone fails eligibility.'
shared['position_sizing'] += ' Define cost_reserve_rate as two times scenario slippage bps/10000 plus applicable per-dollar fees; reserve fixed entry and exit fees before floor-sizing, recompute share count downward until exact fee schedule and cash constraints hold. Each stress scenario independently sizes. Stop uses actual modeled entry ask before cash fee/slippage debits.'
shared['mark_and_order_clock'] = 'Observe each valid regular-session SIP NBBO update, with bid liquidation marks; sizes converted to shares using provider schema. Valid means positive bid<ask, nonnegative sizes, regular quote conditions, not halted. At 10:00 decision require snapshot timestamp within preceding 1 second; otherwise no entry. Mark equity at that snapshot; other held symbols require <=60-second marks, otherwise block new entries and record unresolved coverage. Stale marks retained for accounting only, not risk-pass evidence. Stops checked at every valid update; opening gaps at first valid regular quote. Coincident exits: portfolio halt first, stock stop next, time exit next, entries last. No extended-hours stops; disclose gap risk. Missing executable quotes cannot certify drawdown.'
shared['exit_execution'] = 'On fifth exchange session after entry, at 10:00 schedule sell; at stop/halt schedule immediately. After 5-second latency use first valid bid with displayed size covering entire order. Debit scenario adverse-slippage allowance. If no such quote within 60 seconds, declare unresolved execution: retain bid-marked exposure, fail execution gate, and do not impute partial fills. Only actual documented terminal corporate-action recovery closes unavailable securities. No reused top-of-book inventory inference. All fills hypothetical.'
shared['event_estimand'] = 'Construct matches before execution using only information at decision. Primary outcome covers treatment signals passing the frozen quote-entry rule and three controls with valid full-order-size quote snapshots under identical timing/stop/cost rules. Return is (exit proceeds plus entitlement value minus entry notional minus costs)/entry notional, each event equal weight. Controls each receive the same nominal budget independently for comparison, not funded shorts. Nonfills remain zero-return cash decisions in portfolio; report total signals, fills, missing-controls and missing outcomes separately. Missing held outcome blocks pass; no complete-case success claim. Primary sample coverage must be >=90% of eligible signals; below this is inconclusive.'
shared['bootstrap_algorithm'] = 'For each candidate and method use independent numpy default_rng(20260909). Cluster bootstrap: draw K issuer/sponsor clusters with replacement from K observed clusters, retain every event in each drawn cluster including multiplicities; compute equal-event mean each replication. Time bootstrap: ordered exchange sessions in full evaluation including inactive dates; circular moving blocks, uniformly select start session, append 20 (or robustness 60) consecutive sessions wrapping endpoints until N sessions sampled then truncate to N. Each sampled session contributes all events assigned by entry date, preserving repetitions. Recompute equal-event mean. Empty resamples counted invalid; >1% invalid is inconclusive. 10000 valid draws, max 10102 attempts; linear 2.5th percentile lower bound; no pooling across candidates.'
shared['pass_fail']['execution_gate'] = shared['pass_fail']['execution_gate'].replace('measured 95th percentile adverse slippage', '95th percentile modeled adverse post-latency quote movement')
h1['universe'] = h1['universe'].replace('at least five subsequent sessions', 'at least six subsequent sessions')
h1['controls'] = 'Select exactly three issuance-route funds with different sponsors from each other and treatment, same payment session, asset class and leverage flag, and PIT contractual terms. Sort by absolute distance in prior-close NAV discount using NAV known by entry 09:00, then CIK; greedily select unique sponsors. Need three, otherwise missing-control ledger. Equal-weight matched returns, identical timing/stop/cost rules. Same-fund window 10 sessions before payment excluding other ex/pay dates then known is a secondary diagnostic only.'
h2['controls'] = 'Select exactly three same-type issuers (REIT or BDC), nearest lagged 20-session median dollar turnover absolute distance, then CIK. Use preceding filed exposure taxonomy: REIT residential/office/retail/industrial/healthcare/hotel/storage/timber/diversified/other; BDC diversified-credit only. Assign category from explicit principal-business statement; mixed/unclear goes diversified/other without discretionary reassignment. Require same category and no ex/pay/election event in +/-10 sessions ANNOUNCED by treatment decision. Later announcements never retroactively remove controls. Same dates/stops/costs; missing three controls means not evaluable. All nonbinding capped-cash elections are separate negative controls.'
shared['sample_protocol'] = 'Document-only probes: SEC N-2, N-CSR, N-CSRS, 497 for H1; 8-K and associated exhibits for M2A. Normalize case and whitespace only, apply each stated Boolean phrase search, deduplicate by CIK+event/payment date with earliest matching filing retained; link all amendments through decision cutoff. Sort acceptance timestamp UTC then accession, inspect first 30 search hits (or all if fewer), preserve every hit/exclusion. Report query recall limitation and precision separately. Completeness denominator is all in-scope events among these 30, never just selected complete events. H1 requires >=3 independent funds and >=90% critical completeness; M2A >=10 independent distribution events and >=90%; otherwise data-blocked. Search strings describe a bounded feasibility sample, not full event-universe reconstruction.'
shared['causal_limit'] = 'Matched excess is mechanism-consistent predictive evidence, not proof participant orders caused price changes. Regime selection and unobserved issuer risk remain; no causal claim from these observational controls.'
if (ROOT/'frozen_experiment_plans.json').exists():
    raise SystemExit('Freeze exists: create a versioned amendment; do not overwrite.')
payload={'frozen_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
         'performance_inspected_for_candidates':False,'shared':shared,'experiments':[h1,h2]}
raw=(json.dumps(payload,indent=2)+'\n').encode()
(ROOT/'frozen_experiment_plans.json').write_bytes(raw)
(ROOT/'freeze_receipt.json').write_text(json.dumps({'sha256':hashlib.sha256(raw).hexdigest(),
 'file':'frozen_experiment_plans.json','experiment_ids':[h1['id'],h2['id']],
 'state':'feasibility pending; no return data loaded'},indent=2))
print(json.dumps({'frozen_experiments':2,'sha256':hashlib.sha256(raw).hexdigest()}))
